### ISSUE TITLE
This doesn't seem to be a valid Sublime Text completions file. Aborted.

### ISSUE THREAD

**Issue by Chris951306** [idleberg/atom-atomizr#2]
Adding this package to Sublime went smoothly, but the conversion seems to halt...

Code in question:

Lua.sublime-completions : http://pastebin.com/gACeak5E

Lua.sublime-snippet : http://pastebin.com/VRHiVxAz

Any help? Would greatly appreciate!

Thanks in advance
Christian

**Comment by idleberg** [comment]
First of all: Are you sure you created this issue for the correct package or are you talking its cousin for [Sublime Text](https://github.com/idleberg/sublime-atomizr)?

The answer, however, is the same: valid JSON is expected as input and [comments are not valid](https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr).

```json
{
   "example": {
      // comments are not valid
    }
}
```

Since I expect many people are not aware of this (or simply don't care), I'll see what I can do and add an option to ignore this through a message dialog.

**Comment by Chris951306** [comment]
I am sincerely sorry for not knowing that... Thanks for enlightening me!

**Comment by idleberg** [comment]
Both packages, [atom-atomizr](https://github.com/idleberg/atom-atomizr) and [sublime-atomizr](https://github.com/idleberg/sublime-atomizr), can now convert snippets as well
